name: instaport_rider
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7
  permission_handler: ^11.0.1
  flutter_polyline_points: ^2.0.0
  flutter_spinkit: ^5.2.0
  http: ^1.2.2
  map_location_picker: ^1.3.0
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.6
  uuid: ^4.2.1
  text_scroll: ^0.2.0
  intl: ^0.19.0
  url_launcher: ^6.2.2
  geolocator: ^13.0.1
  firebase_core: ^3.3.0
  firebase_database: ^11.0.4
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.2.2
  mask_text_input_formatter: ^2.9.0
  fluttertoast: ^8.2.4
  image: ^4.1.7
  flutter_inappwebview: ^6.0.0
  firebase_messaging: ^15.0.4
  flutter_launcher_icons: ^0.14.1
  background_location: ^0.13.0
  file_picker: ^8.1.2
  widgets_to_image: ^1.0.0
  path_provider: ^2.1.4
  path: ^1.9.0
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/main/main.png"

flutter:

  uses-material-design: true

  assets:
    - assets/